name: Publish Packagist
on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  publish:
    name: publish
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Update Packagist
        run: |-
          curl --fail-with-body -X POST -H 'Content-Type: application/json' "https://packagist.org/api/update-package?username=${PACKAGIST_USERNAME}&apiToken=${PACKAGIST_SAFE_KEY}" -d '{"repository":"https://www.github.com/jacobzim-stl/pubtest-php"}'
        env:
          PACKAGIST_USERNAME: ${{ secrets.PHP_PUBLISHING_TEST_PACKAGIST_USERNAME || secrets.PACKAGIST_USERNAME }}
          PACKAGIST_SAFE_KEY: ${{ secrets.PHP_PUBLISHING_TEST_PACKAGIST_SAFE_KEY || secrets.PACKAGIST_SAFE_KEY }}